export const OidcConfig = {
  localhost: {
    env: "dev",
    wrapper_endpoint: "https://uat.beatapps.net/IdSWrapper/pod/IdsWrapperServices/api/",
    authority: "https://uat.beatapps.net/identity/uat/beat/sts/",
    endsession_endpoint: "https://uat.beatapps.net/identity/uat/beat/sts/connect/endsession",
    introspect_endpoint: "https://uat.beatapps.net/identity/uat/beat/sts/connect/introspect",
    client_id: "beat-foliosure-pod-pec-localhost-client-id_app",
    redirect_uri: "http://localhost:4200/#/in",
    response_type: "code",
    scope: "openid profile beat-foliosure-pod-pec-localhost-client-id_services beat-ids-wrapper-api-pod-resource-id auth-admin-client-id_api",
    loadUserInfo: true,
    silent_redirect_uri: `${document.location.origin}/#/refresh`,
    clientName: "pod",
    introspectHeader: "YmVhdC1mb2xpb3N1cmUtcG9kLXBlYy1sb2NhbGhvc3QtY2xpZW50LWlkX3NlcnZpY2VzOjYyNTk3ODg2LTYyRTQtNDMwOC05Q0Y2LTZFOEFCNTJBQUYwMA=="
  },
  dev: {
    env: "dev",
    wrapper_endpoint: "https://uat.beatapps.net/IdSWrapper/pod/IdsWrapperServices/api/",
    authority: "https://uat.beatapps.net/identity/uat/beat/sts/",
    endsession_endpoint: "https://uat.beatapps.net/identity/uat/beat/sts/connect/endsession",
    introspect_endpoint: "https://uat.beatapps.net/identity/uat/beat/sts/connect/introspect",
    client_id: "beat-foliosure-pod-pec-dev-client-id",
    redirect_uri: "https://dev.beatapps.net/foliosure/dev/pod/app/#/in",
    response_type: "code",
    scope: "openid profile beat-foliosure-pod-pec-dev-client-id_services beat-ids-wrapper-api-pod-resource-id auth-admin-client-id_api",
    loadUserInfo: true,
    silent_redirect_uri: `${document.location.origin}/foliosure/dev/pod/app/#/refresh`,
    clientName: "pod",
    introspectHeader: "YmVhdC1mb2xpb3N1cmUtcG9kLXBlYy1kZXYtY2xpZW50LWlkX3NlcnZpY2VzOjVFNUQyMUJCLUQ4RTQtNEQ2NC05MDI0LTlGMDc5MEI5MDRGOA=="
  },
  feature: {
    env: "dev",
    wrapper_endpoint: "https://uat.beatapps.net/IdSWrapper/pod/IdsWrapperServices/api/",
    authority: "https://uat.beatapps.net/identity/uat/beat/sts/",
    endsession_endpoint: "https://uat.beatapps.net/identity/uat/beat/sts/connect/endsession",
    introspect_endpoint: "https://uat.beatapps.net/identity/uat/beat/sts/connect/introspect",
    client_id: "beat-foliosure-pod-pec-feature-client-id",
    redirect_uri: "https://dev.beatapps.net/foliosure/feature/pod/app/#/in",
    response_type: "code",
    scope: "openid profile beat-foliosure-pod-pec-feature-client-id_services beat-ids-wrapper-api-pod-resource-id auth-admin-client-id_api",
    loadUserInfo: true,
    silent_redirect_uri: `${document.location.origin}/foliosure/feature/pod/app/#/refresh`,
    clientName: "pod",
    introspectHeader: "YmVhdC1mb2xpb3N1cmUtcG9kLXBlYy1mZWF0dXJlLWNsaWVudC1pZF9zZXJ2aWNlczpBODY4MjgyQS0wNTc1LTRFN0UtODg5NC1GNzJENDIwRTc4QTI="
  },
  test: [
    {
      env: "test",
      wrapper_endpoint: "https://uat.beatapps.net/IdSWrapper/pod/IdsWrapperServices/api/",
      authority: "https://uat.beatapps.net/identity/uat/beat/sts/",
      endsession_endpoint: "https://uat.beatapps.net/identity/uat/beat/sts/connect/endsession",
      introspect_endpoint: "https://uat.beatapps.net/identity/uat/beat/sts/connect/introspect",
      client_id: "beat-foliosure-pod-pec-test-client-id",
      redirect_uri: "https://test.beatapps.net/foliosure/test/pod/app/#/in",
      response_type: "code",
      scope: "openid profile beat-foliosure-pod-pec-test-client-id_services beat-ids-wrapper-api-pod-resource-id auth-admin-client-id_api",
      loadUserInfo: true,
      silent_redirect_uri: `${document.location.origin}/foliosure/test/pod/app/#/refresh`,
      clientName: "pod",
      introspectHeader: "YmVhdC1mb2xpb3N1cmUtcG9kLXBlYy10ZXN0LWNsaWVudC1pZF9zZXJ2aWNlczpFRjI3NzU1Ri1FRkNFLTQ3MUItQkIzRS1GNTdFRDMwM0RGRTc="
    },
    {
      wrapper_endpoint: "https://uat.beatapps.net/IdSWrapper/pod/IdsWrapperServices/api/",
      authority: "https://uat.beatapps.net/identity/uat/beat/sts/",
      endsession_endpoint: "https://uat.beatapps.net/identity/uat/beat/sts/connect/endsession",
      introspect_endpoint: "https://uat.beatapps.net/identity/uat/beat/sts/connect/introspect",
      client_id: "beat-foliosure-pod-pec-test-podb-client-id",
      redirect_uri: "https://test.beatapps.net/foliosure/test/pod-b/app/#/in",
      response_type: "code",
      scope: "openid profile beat-foliosure-pod-pec-test-podb-client-id_services beat-ids-wrapper-api-pod-resource-id auth-admin-client-id_api",
      loadUserInfo: true,
      silent_redirect_uri: `${document.location.origin}/foliosure/test/pod-b/app/#/refresh`,
      clientName: "pod-b",
      introspectHeader: "YmVhdC1mb2xpb3N1cmUtcG9kLXBlYy10ZXN0LWNsaWVudC1pZF9zZXJ2aWNlczpFRjI3NzU1Ri1FRkNFLTQ3MUItQkIzRS1GNTdFRDMwM0RGRTc="
    }
  ],
  perf1: {
    env: "perf",
    wrapper_endpoint: "https://uat.beatapps.net/IdSWrapper/pod/IdsWrapperServices/api/",
    authority: "https://perf-test01.beatapps.net/identity/perf1/pod/sts/",
    endsession_endpoint: "https://perf-test01.beatapps.net/identity/perf1/pod/sts/connect/endsession",
    introspect_endpoint: "https://perf-test01.beatapps.net/identity/perf1/pod/sts/connect/introspect",
    client_id: "beat-foliosure-pod-pec-perf1-client-id",
    redirect_uri: "https://perf-test01.beatapps.net/foliosure/perf1/pod/app/#/in",
    response_type: "code",
    scope: "openid profile beat-foliosure-pod-pec-perf-client-id_services",
    loadUserInfo: true,
    silent_redirect_uri: `${document.location.origin}/foliosure/perf1/pod/app/#/refresh`,
    clientName: "pod",
    introspectHeader: "YmVhdC1mb2xpb3N1cmUtcG9kLXBlYy1wZXJmLWNsaWVudC1pZF9zZXJ2aWNlczpCRDE3QTQxNC1DMjVCLTQwMkItODNEQi01QThBOTQ3Q0I0QUE="
  },
  perf2: {
    env: "perf",
    wrapper_endpoint: "https://uat.beatapps.net/IdSWrapper/pod/IdsWrapperServices/api/",
    authority: "https://perf-test02.beatapps.net/identity/perf2/pod/sts/",
    endsession_endpoint: "https://perf-test02.beatapps.net/identity/perf2/pod/sts/connect/endsession",
    introspect_endpoint: "https://perf-test02.beatapps.net/identity/perf2/pod/sts/connect/introspect",
    client_id: "beat-foliosure-pod-pec-perf2-client-id",
    redirect_uri: "https://perf-test02.beatapps.net/foliosure/perf2/pod/app/#/in",
    response_type: "code",
    scope: "openid profile beat-foliosure-pod-pec-perf-client-id_services",
    loadUserInfo: true,
    silent_redirect_uri: `${document.location.origin}/foliosure/perf2/pod/app/#/refresh`,
    clientName: "pod",
    introspectHeader: "YmVhdC1mb2xpb3N1cmUtcG9kLXBlYy1wZXJmLWNsaWVudC1pZF9zZXJ2aWNlczpCRDE3QTQxNC1DMjVCLTQwMkItODNEQi01QThBOTQ3Q0I0QUE="
  },
  uat: [{
    env: "uat",
    wrapper_endpoint: "https://uat.beatapps.net/IdSWrapper/pod/IdsWrapperServices/api/",
    authority: "https://uat.beatapps.net/identity/uat/beat/sts/",
    endsession_endpoint: "https://uat.beatapps.net/identity/uat/beat/sts/connect/endsession",
    introspect_endpoint: "https://uat.beatapps.net/identity/uat/beat/sts/connect/introspect",
    client_id: "beat-foliosure-pod-pec-uat-client-id",
    redirect_uri: "https://uat.beatapps.net/foliosure/uat/pod/app/#/in",
    response_type: "code",
    scope: "openid profile beat-foliosure-pod-pec-uat-client-id_services beat-ids-wrapper-api-pod-resource-id auth-admin-client-id_api",
    loadUserInfo: true,
    silent_redirect_uri: `${document.location.origin}/foliosure/uat/pod/app/#/refresh`,
    clientName: "pod",
    introspectHeader: "YmVhdC1mb2xpb3N1cmUtcG9kLXBlYy11YXQtY2xpZW50LWlkX3NlcnZpY2VzOkREMTJGMTNGLTE1REItNDNBMC04NjVELUM0NTEzOUNEM0JFMg=="
  },
  {   
    wrapper_endpoint: "https://uat.beatapps.net/IdSWrapper/pod/IdsWrapperServices/api/",
    authority: "https://uat.beatapps.net/identity/uat/beat/sts/",
    endsession_endpoint: "https://uat.beatapps.net/identity/uat/beat/sts/connect/endsession",
    introspect_endpoint: "https://uat.beatapps.net/identity/uat/beat/sts/connect/introspect",
    client_id: "beat-foliosure-pod-pec-uat-podb-client-id",
    redirect_uri: "https://uat.beatapps.net/foliosure/uat/pod-b/app/#/in",
    response_type: "code",
    scope: "openid profile beat-foliosure-pod-pec-uat-podb-client-id_services beat-ids-wrapper-api-pod-resource-id auth-admin-client-id_api",
    loadUserInfo: true,
    silent_redirect_uri: `${document.location.origin}/foliosure/uat/pod-b/app/#/refresh`,
    clientName: "pod-b",
    introspectHeader: "YmVhdC1mb2xpb3N1cmUtcG9kLXBlYy11YXQtY2xpZW50LWlkX3NlcnZpY2VzOkREMTJGMTNGLTE1REItNDNBMC04NjVELUM0NTEzOUNEM0JFMg=="
  },
  {
    wrapper_endpoint: "https://uat.beatapps.net/IdSWrapper/pod/IdsWrapperServices/api/",
    authority: "https://uat.beatapps.net/identity/uat/sso/sts/",
    endsession_endpoint: "https://uat.beatapps.net/identity/uat/sso/sts/connect/endsession",
    introspect_endpoint: "https://uat.beatapps.net/identity/uat/sso/sts/connect/introspect",
    client_id: "beat-foliosure-pod-pec-taabo-client-id",
    redirect_uri: "https://uat.beatapps.net/foliosure/uat/taabo/app/#/in",
    response_type: "code",
    scope: "openid profile beat-foliosure-pod-pec-taabo-client-id_services beat-ids-wrapper-api-pod-resource-id auth-admin-client-id_api",
    loadUserInfo: true,
    silent_redirect_uri: `${document.location.origin}/foliosure/uat/taabo/app/#/refresh`,
    clientName: "taabo",
    introspectHeader: "YmVhdC1mb2xpb3N1cmUtcG9kLXBlYy11YXQtY2xpZW50LWlkX3NlcnZpY2VzOkREMTJGMTNGLTE1REItNDNBMC04NjVELUM0NTEzOUNEM0JFMg=="
  }],
  prod:
  [
    {
      env:"prod",
      wrapper_endpoint:"https://identity.beatapps.net/IdSWrapper/pod/IdsWrapperServices/api/",
      authority: "https://demo.identity.beat-services.net/sts/",
      endsession_endpoint : "https://demo.identity.beat-services.net/sts/connect/endsession",
      introspect_endpoint : "https://demo.identity.beat-services.net/sts/connect/introspect",
      client_id: "beat-foliosure-pod-pec-demo-client-id",
      redirect_uri: "https://demo.beatfoliosure.com/app/#/in",
      response_type: "code",
      scope: "openid profile beat-foliosure-pod-pec-demo-client-id_services",
      loadUserInfo: true,
      silent_redirect_uri: "https://demo.beatfoliosure.com/app/#/refresh",
      clientName: "demo",
      introspectHeader : "YmVhdC1mb2xpb3N1cmUtcG9kLXBlYy1kZW1vLWNsaWVudC1pZF9zZXJ2aWNlczpCOUQ5MjM2Qi0zMjg1LTRDRTgtQTdEMS1FNDUyRDU4RDQzQjA="
    },
    {
      wrapper_endpoint:"https://identity.beatapps.net/IdSWrapper/pod/IdsWrapperServices/api/",
      authority: "https://demo.identity.beat-services.net/sts/",
      endsession_endpoint : "https://demo.identity.beat-services.net/sts/connect/endsession",
      introspect_endpoint : "https://demo.identity.beat-services.net/sts/connect/introspect",
      client_id: "beat-foliosure-pod-pec-enshi-client-id",
      redirect_uri: "https://enshi.beatfoliosure.com/app/#/in",
      response_type: "code",
      scope: "openid profile beat-foliosure-pod-pec-enshi-client-id_services",
      loadUserInfo: true,
      silent_redirect_uri: "https://enshi.beatfoliosure.com/app/#/refresh",
      clientName: "enshi",
      introspectHeader : "YmVhdC1mb2xpb3N1cmUtcG9kLXBlYy1lbnNoaS1jbGllbnQtaWRfc2VydmljZXM6RTk4Qzk0QkQtOUEzMi00RUYxLTlFNzktQUY0OUY0NzVCNDJD"
      },
      {
        wrapper_endpoint: "https://identity.beatapps.net/IdSWrapper/pod/IdsWrapperServices/api/",
        authority: "https://identity.beat-services.net/sts/",
        endsession_endpoint: "https://identity.beat-services.net/sts/connect/endsession",
        introspect_endpoint: "https://identity.beat-services.net/sts/connect/introspect",
        client_id: "beat-foliosure-pod-pec-taabo-ch-client-id",
        redirect_uri: "https://taabo-ch.beatfoliosure.com/app/#/in",
        response_type: "code",
        scope: "openid profile beat-foliosure-pod-pec-taaboch-prod-client-id_services",
        loadUserInfo: true,
        silent_redirect_uri: "https://taabo-ch.beatfoliosure.com/app/#/refresh",
        clientName: "taabo-ch",
        introspectHeader: "YmVhdC1mb2xpb3N1cmUtcG9kLXBlYy1lbnNoaS1jbGllbnQtaWRfc2VydmljZXM6RTk4Qzk0QkQtOUEzMi00RUYxLTlFNzktQUY0OUY0NzVCNDJD"
      },
      {
        wrapper_endpoint: "https://identity.beatapps.net/IdSWrapper/pod/IdsWrapperServices/api/",
        authority: "https://identity.beat-services.net/sts/",
        endsession_endpoint: "https://identity.beat-services.net/sts/connect/endsession",
        introspect_endpoint: "https://identity.beat-services.net/sts/connect/introspect",
        client_id: "beat-foliosure-pod-pec-larissa-client-id",
        redirect_uri: "https://larissa.beatfoliosure.com/app/#/in",
        response_type: "code",
        scope: "openid profile beat-foliosure-pod-pec-larissa-prod-client-id_services",
        loadUserInfo: true,
        silent_redirect_uri: "https://larissa.beatfoliosure.com/app/#/refresh",
        clientName: "larissa",
        introspectHeader: "YmVhdC1mb2xpb3N1cmUtcG9kLXBlYy1lbnNoaS1jbGllbnQtaWRfc2VydmljZXM6RTk4Qzk0QkQtOUEzMi00RUYxLTlFNzktQUY0OUY0NzVCNDJD"
      },
      {
        wrapper_endpoint: "https://monmouth.identity.beatapps.net/IdSWrapper/pod/IdsWrapperServices/api/",
        authority: "https://monmouth.identity.beat-services.net/sts/",
        endsession_endpoint: "https://monmouth.identity.beat-services.net/sts/connect/endsession",
        introspect_endpoint: "https://monmouth.identity.beat-services.net/sts/connect/introspect",
        client_id: "beat-foliosure-pod-pec-monmouth-client-id",
        redirect_uri: "https://monmouth.beatfoliosure.com/app/#/in",
        response_type: "code",
        scope: "openid profile beat-foliosure-pod-pec-monmouth-prod-client-id_services",
        loadUserInfo: true,
        silent_redirect_uri: "https://monmouth.beatfoliosure.com/app/#/refresh",
        clientName: "monmouth",
        introspectHeader: "YmVhdC1mb2xpb3N1cmUtcG9kLXBlYy1lbnNoaS1jbGllbnQtaWRfc2VydmljZXM6RTk4Qzk0QkQtOUEzMi00RUYxLTlFNzktQUY0OUY0NzVCNDJD"
      },
      {
        wrapper_endpoint: "https://identity.beatapps.net/IdSWrapper/pod/IdsWrapperServices/api/",
        authority: "https://identity.beat-services.net/sts/",
        endsession_endpoint: "https://identity.beat-services.net/sts/connect/endsession",
        introspect_endpoint: "https://identity.beat-services.net/sts/connect/introspect",
        client_id: "beat-foliosure-pod-pec-exeter-client-id",
        redirect_uri: "https://exeter.beatfoliosure.com/app/#/in",
        response_type: "code",
        scope: "openid profile beat-foliosure-pod-pec-exeter-prod-client-id_services",
        loadUserInfo: true,
        silent_redirect_uri: "https://exeter.beatfoliosure.com/app/#/refresh",
        clientName: "exeter",
        introspectHeader: "YmVhdC1mb2xpb3N1cmUtcG9kLXBlYy1lbnNoaS1jbGllbnQtaWRfc2VydmljZXM6RTk4Qzk0QkQtOUEzMi00RUYxLTlFNzktQUY0OUY0NzVCNDJD"
      },
      {
        wrapper_endpoint:"https://identity.beatapps.net/IdSWrapper/pod/IdsWrapperServices/api/",
        authority: "https://demo.identity.beat-services.net/sts/",
        endsession_endpoint : "https://demo.identity.beat-services.net/sts/connect/endsession",
        introspect_endpoint : "https://demo.identity.beat-services.net/sts/connect/introspect",
        client_id: "beat-foliosure-pod-pec-trial-client-id",
        redirect_uri: "https://trial.beatfoliosure.com/app/#/in",
        response_type: "code",
        scope: "openid profile beat-foliosure-pod-pec-trial-client-id_services",
        loadUserInfo: true,
        silent_redirect_uri: "https://trial.beatfoliosure.com/app/#/refresh",
        clientName: "trial",
        introspectHeader : "YmVhdC1mb2xpb3N1cmUtcG9kLXBlYy1kZW1vLWNsaWVudC1pZF9zZXJ2aWNlczpCOUQ5MjM2Qi0zMjg1LTRDRTgtQTdEMS1FNDUyRDU4RDQzQjA="
      },
      {
        wrapper_endpoint: "https://identity.beatapps.net/IdSWrapper/pod/IdsWrapperServices/api/",
        authority: "https://identity.beat-services.net/sts/",
        endsession_endpoint: "https://identity.beat-services.net/sts/connect/endsession",
        introspect_endpoint: "https://identity.beat-services.net/sts/connect/introspect",
        client_id: "beat-foliosure-pod-pec-pizarro-client-id",
        redirect_uri: "https://pizarro.beatfoliosure.com/app/#/in",
        response_type: "code",
        scope: "openid profile beat-foliosure-pod-pec-pizarro-prod-client-id_services",
        loadUserInfo: true,
        silent_redirect_uri: "https://pizarro.beatfoliosure.com/app/#/refresh",
        clientName: "pizarro",
        introspectHeader: "YmVhdC1mb2xpb3N1cmUtcG9kLXBlYy1lbnNoaS1jbGllbnQtaWRfc2VydmljZXM6RTk4Qzk0QkQtOUEzMi00RUYxLTlFNzktQUY0OUY0NzVCNDJD"
      },
  ],
  isIdsEnabled : true,
  applicationName : "BEAT FolioSure"
}
