export class Document {
    public id: string;
    public name: string;
    public extension: string;
    public documentType: string;
    public documentSubType: string;
    public dateOfDocument: Date;
    public firmId: number;
    public fundId: number;
    public portfolioCompanyId: number;
    public dealId: number;
    public createdBy: string;
    public comment: string;
    public modifiedBy: string;
    public version: string;
    public folderName: string;
    public documentTypeName: string;
    public uploadedBy: string;
    public createdOn: Date;
    public documentSubTypeName: string;
    public firmName: string;
    public fundName: string;
    public portfolioCompanyName: string;
    public dealName: string;
    public path: string;
    public modifiedOn : Date;
    public tags: string;
    public assignedTo: string;
    public assignedToNames: string[];
    public status: string;
    public statusId: number;
    public encryptedDocumentId : string;
}
